name = "probyte-api"
main = "server/worker.ts"
account_id = "730a047f145d2d523d2219aa0c04ee66"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
CORS_ORIGIN = "*"
TRUST_PROXY = "true"
PUBLIC_APP_URL = "https://probyte.pages.dev"
